name: SP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
  pull_request:
   paths:
      - 'sp/src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create project
        run: cd sp/src;devtools/bin/vpc.exe /sdk2k24 /2013 +game /mksln sdk2k24.sln

      - name: Build project
        run: cd sp/src;devenv sdk2k24.sln /Build Release

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz sp/game/mod_sdk2k24/bin

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: sp_sdk2k24
          path: Windows.tar.xz
